#!/bin/bash

FILE=y1all
#TAG=y1a1-v13
#FILE=y1s82
#TAG=y1a1-v11
#FILE=y1_00177358
TAG=y1a1-v02

./run_wq_exp.py --njobs=50 --cores_per_job=4 --file=$FILE --tag=cats --cmd="./build_psf_cats.py --tag=$TAG --work=~/work/psfex_rerun/$TAG"
#./run_wq_exp.py --njobs=200 --cores_per_job=4 --file=$FILE --tag=cats --cmd="./build_psf_cats.py --tag=$TAG --work=~/work/psfex_rerun/$TAG --use_piff"
#./run_wq_exp.py --njobs=200 --cores_per_job=4 --file=$FILE --tag=cats --cmd="./build_psf_cats.py --tag=$TAG --work=~/work/psfex_rerun/$TAG --reference_tag=y1a1-v02"
