#!/bin/bash

#FILE=y1all
FILE=y3test
TAG=y3a1-v01

#./run_wq_exp.py --njobs=1 --cores_per_job=1 --file=$FILE --tag=fs --cmd="./plot_fs.py --tag=$TAG --work=~/work/psfex_rerun/$TAG --make_stats --no_plot"
#./run_wq_exp.py --njobs=200 --cores_per_job=1 --file=$FILE --tag=fs --cmd="./plot_fs.py --tag=$TAG --work=~/work/psfex_rerun/$TAG --make_stats"
./run_wq_exp.py --njobs=200 --cores_per_job=1 --file=$FILE --tag=fs --cmd="./plot_fs.py --tag=$TAG --work=~/work/psfex_rerun/$TAG --do_plot"
