#!/bin/bash

#FILE=zone029.riz
#FILE=ten_zones.z
#FILE=zone001.z
#FILE=ally3.riz
FILE=zones03.riz
#FILE=redo_exp
#FILE=test1
TAG=y3a1-v24

#/bin/rm -f $DESDATA/EXTRA/blacklists/psfex-$TAG.txt
/bin/rm -rf ~/work/y3_piff/$TAG/*
./run_wq_exp.py --njobs=250 --cores_per_job=1 --file=$FILE --tag=go --cmd="./run_piff.py --mag_cut=1 --max_mag=21 --work=~/work/y3_piff/$TAG --tag=$TAG --rm_files=1 --reserve=0.2 --use_ngmix --blacklist=0 --clear_output=0 --get_psfex"
#./run_condor.py --file=$FILE --tag=$TAG 
