#!/bin/bash

#FILE=zone029.riz
#TAG=y1a1-v13
#FILE=ten_zones.riz
#FILE=ally3.riz
#FILE=zone008.z
FILE=zones03.riz
TAG=y3a1-v26

./run_wq_exp.py --njobs=1 --cores_per_job=12 --file=$FILE --tag=mag --cmd="./plot_mag.py --file=$FILE --tag=$TAG --work=~/work/y3_piff/$TAG --frac=0.1"
#./run_wq_exp.py --njobs=1 --cores_per_job=12 --file=$FILE --tag=mag --cmd="./plot_mag.py --file=$FILE --tag=$TAG --work=~/work/y3_piff/$TAG --use_reserved"
./run_wq_exp.py --njobs=1 --cores_per_job=12 --file=$FILE --tag=mag_pf --cmd="./paper_figures.py --file=$FILE --tag=$TAG --work=~/work/y3_piff/$TAG --frac=0.1"
#./run_wq_exp.py --njobs=1 --cores_per_job=12 --file=$FILE --tag=mag --cmd="./plot_mag.py --file=$FILE --tag=$TAG --work=~/work/y3_piff/$TAG --use_psfex --frac=0.1"
#./run_wq_exp.py --njobs=1 --cores_per_job=12 --file=$FILE --tag=mag_pf --cmd="./paper_figures.py --file=$FILE --tag=$TAG --work=~/work/y3_piff/$TAG --use_psfex --frac=0.1"
