#!/bin/bash

FILE=y1x
#FILE=test1_exp
TAG=y1a1-v02

./run_wq_exp.py --njobs=10 --cores_per_job=4 --file=$FILE --tag=fs --cmd="./plot_fs.py --tag=$TAG --work=~/work/psfex_rerun/$TAG"
#./run_wq_exp.py --njobs=1 --cores_per_job=4 --file=$FILE --tag=fs --cmd="./plot_fs.py --tag=$TAG --work=~/work/psfex_rerun/$TAG --single_ccd"
