#!/bin/bash

#FILE=zone033.riz
#TAG=y3a1-v16
#FILE=ten_zones.riz
#FILE=ally3.g
#FILE=zones03.riz
FILE=ally3.riz
TAG=y3a1-v29

#./run_rho2.py --tag=$TAG --work=~/work/y3_piff/$TAG --file=$FILE --use_reserved
./plot_rho.py --file=$FILE --tag=$TAG --work=~/work/y3_piff/$TAG

