#!/bin/bash

FILE=gold_exp
TAG=v4

./run_wq_exp.py --debug --njobs=1 --file=$FILE --tag=rm --cmd="./run_psfex.py --use_findstars=0 --use_tapebumps=0 --rm_files=1 --run_psfex=0 --work=~/work/psfex_rerun/$TAG --tag=$TAG"
