#!/bin/bash

#FILE=y1all
#TAG=y1a1-v02
#FILE=zone029.riz
#TAG=y3a1-v16
#FILE=ten_zones.riz
#FILE=zones03x.r
FILE=ally3.riz
TAG=y3a1-v29

./run_wq_exp.py --njobs=1 --cores_per_job=12 --file=$FILE --tag=rho2 --cmd="./run_rho2.py --tag=$TAG --work=~/work/y3_piff/$TAG --use_reserved --subtract_mean --bands=riz --do_rho0 --max_mag=21"
#./run_wq_exp.py --njobs=1 --cores_per_job=12 --file=$FILE --tag=rho2 --cmd="./run_rho2.py --tag=$TAG --work=~/work/y3_piff/$TAG"
#./run_wq_exp.py --njobs=1 --cores_per_job=12 --file=$FILE --tag=rho2 --cmd="./run_rho2.py --tag=$TAG --work=~/work/y3_piff/$TAG --use_psfex --use_reserved"
