#!/bin/bash

FILE=ally3.riz
#FILE=redo_exp
TAG=y3a1-v23

./run_wq_exp.py --njobs=1 --cores_per_job=1 --file=$FILE --tag=verify --cmd="python verify.py --file=$FILE --tag=$TAG --work=~/work/y3_piff/$TAG"
