#!/bin/bash

FILE=y1all_r
TAG=y1a1-v12
#FILE=y1s82
#TAG=y1a1-v11
#FILE=y1_00177358
#TAG=y1a1-v02

./run_wq_exp.py --njobs=100 --cores_per_job=1 --file=$FILE --tag=cats --cmd="./build_psf_cats.py --tag=$TAG --work=~/work/psfex_rerun/$TAG --use_piff"
