#!/bin/bash

FILE=des1000+0209_exp
#FILE=tb-y1a1
TAG=y1a1-v04

./run_wq_exp.py --njobs=500 --cores_per_job=1 --file=$FILE --tag=cats --cmd="./build_psf_cats.py --tag=$TAG --work=~/work/psfex_rerun/$TAG"
