#!/bin/bash

DATE=20140920
FILE=test_exp
TAG=v3

./run_wq_exp.py --njobs=1 --cores_per_job=4 --file=$FILE --submit_dir=~/work/submit_rho_$DATE --cmd="./run_rho.py --exp_match=\"*_[0-9][0-9].fits*\" --work=~/work/psfex_rerun/$TAG"
