#!/bin/bash

DATE=20150313_rho2
FILE=gold_exp
TAG=v4

./run_wq_exp.py --njobs=1 --cores_per_job=12 --file=$FILE --submit_dir=~/work/submit_$DATE --cmd="./run_rho2.py --tag=$TAG --work=~/work/psfex_rerun/$TAG"
