#!/bin/bash

DATE=20151216_rho2
FILE=y1spte_r
TAG=v1

./run_wq_exp.py --njobs=1 --cores_per_job=12 --file=$FILE --submit_dir=~/work/submit_$DATE --cmd="./run_rho2.py --tag=$TAG --work=~/work/psfex_rerun/$TAG"
