#!/bin/bash

#FILE=y1all
FILE=y1all_r
TAG=y1a1-v13

./run_wq_exp.py --njobs=1 --file=$FILE --tag=setup --cmd="./run_psfex.py --exp_match=\"*_[0-9][0-9].fits*\" --work=~/work/psfex_rerun/$TAG --tag=$TAG --use_findstars=0 --use_tapebumps=0 --run_psfex=0 --clear_output"
