#!/bin/bash

version=v4
user=mjarvis@carver.nersc.gov
nersc=/global/project/projectdirs/des/wl/desdata

for run in $( ls "$DESDATA/EXTRA/red" ); do
    echo $run
    psfex_dir="EXTRA/red/$run/psfex-rerun"
    if [ -e "$DESDATA/$psfex_dir/$version" ]
    then
        cmd="ssh $user 'mkdir -p $nersc/$psfex_dir'"
        echo "  " $cmd
        eval "$cmd"

        cmd="rsync -rz $DESDATA/$psfex_dir/$version $user:$nersc/$psfex_dir"
        echo "  " $cmd
        eval "$cmd"
    fi
done

echo "rsync -rz $DESDATA/EXTRA/blacklists/psfex-sva1x-$version.txt $user:$nersc/EXTRA/blacklists"
rsync -rz $DESDATA/EXTRA/blacklists/psfex-sva1x-$version.txt $user:$nersc/EXTRA/blacklists
